name: 3DR1
channels:
  - aihabitat
  - nvidia/label/cuda-11.8.0
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.15.2=hb03c661_0
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h3394656_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.0=py39h74842e3_2
  - cuda-cccl=11.8.89=0
  - cuda-command-line-tools=11.8.0=0
  - cuda-compiler=11.8.0=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cuobjdump=11.8.86=0
  - cuda-cupti=11.8.87=0
  - cuda-cuxxfilt=11.8.86=0
  - cuda-documentation=11.8.86=0
  - cuda-driver-dev=11.8.89=0
  - cuda-gdb=11.8.86=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=11.8.86=0
  - cuda-nsight-compute=11.8.0=0
  - cuda-nvcc=11.8.89=0
  - cuda-nvdisasm=11.8.86=0
  - cuda-nvml-dev=11.8.86=0
  - cuda-nvprof=11.8.87=0
  - cuda-nvprune=11.8.86=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-nvvp=11.8.87=0
  - cuda-profiler-api=11.8.86=0
  - cuda-sanitizer-api=11.8.86=0
  - cuda-toolkit=11.8.0=0
  - cuda-tools=11.8.0=0
  - cuda-visual-tools=11.8.0=0
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - dbus=1.13.6=h5008d03_3
  - double-conversion=3.3.1=h5888daf_0
  - expat=2.7.3=hecca717_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=ha770c72_0
  - gds-tools=1.4.0.31=0
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - graphite2=1.3.14=hecca717_2
  - habitat-sim-mutex=1.0=display_bullet
  - harfbuzz=11.0.0=h76408a6_0
  - icu=75.1=he02047a_0
  - importlib-resources=6.5.2=pyhd8ed1ab_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.7=py39h74842e3_0
  - krb5=1.21.3=h659f571_0
  - lcms2=2.18=h0c24ade_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_104
  - lerc=4.0.0=h0aef613_1
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcblas=3.11.0=5_h0358290_openblas
  - libclang-cpp20.1=20.1.8=default_h99862b1_7
  - libclang13=21.1.0=default_h746c552_1
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcufile=1.4.0.31=0
  - libcufile-dev=1.4.0.31=0
  - libcups=2.3.3=hb8b1518_5
  - libcurand=10.3.0.86=0
  - libcurand-dev=10.3.0.86=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_15
  - libgcc-ng=15.2.0=h69a702a_15
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.0=h2ff4ddf_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=he0feb66_15
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - libllvm20=20.1.8=hecd9e04_0
  - libllvm21=21.1.0=hecd9e04_0
  - liblzma=5.8.1=hb9d3cd8_2
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopengl=1.7.0=ha4b6fd6_2
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.53=h421ea60_0
  - libpq=17.7=h5c52fec_1
  - libsqlite=3.51.1=h0c1763c_0
  - libstdcxx=15.2.0=h934c35e_15
  - libstdcxx-ng=15.2.0=hdf11a46_15
  - libtiff=4.7.1=h9d88235_1
  - libuuid=2.41.2=h5347b49_1
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.11.0=he8b52b9_0
  - libxml2=2.13.9=h04c0eec_0
  - libxslt=1.1.43=h7a3aeb2_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvmlite=0.43.0=py39hf8b6b1a_1
  - matplotlib=3.9.4=py39hf3d152e_0
  - matplotlib-base=3.9.4=py39h16632d1_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql-common=9.0.1=h266115a_6
  - mysql-libs=9.0.1=he0572af_6
  - ncurses=6.5=h2d0b736_3
  - nsight-compute=2022.3.0.22=0
  - numba=0.60.0=py39h0320e7d_0
  - numpy=1.26.4=py39h474f0d3_0
  - openjpeg=2.5.4=h55fea9a_0
  - openldap=2.6.10=he970967_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pcre2=10.44=hc749103_2
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pyside6=6.9.0=py39h0383914_0
  - python=3.9.23=hc30ae73_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.9=8_cp39
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.0=h6441bc3_0
  - quaternion=2023.0.4=py39hf15bc26_0
  - readline=8.2=h8c095d6_2
  - scipy=1.13.1=py39haf93ffa_0
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - smmap=3.0.5=pyh44b312d_0
  - tk=8.6.13=noxft_ha0e22de_103
  - tornado=6.5.2=py39hd399759_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing_extensions=4.14.1=pyhe01879c_0
  - unicodedata2=16.0.0=py39h8cd3c5a_0
  - wayland=1.24.0=hd6090a7_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - withbullet=2.0=0
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.6=hb03c661_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxinerama=1.1.5=h5888daf_1
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - absl-py==2.3.1
      - accelerate==0.27.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - braceexpand==0.1.7
      - cachetools==6.2.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.1.8
      - clip==1.0
      - cloudpickle==3.1.2
      - cmake==4.2.0
      - cython==3.2.2
      - datasets==4.4.1
      - decorator==5.2.1
      - deepspeed==0.18.3
      - dill==0.4.0
      - einops==0.8.1
      - exceptiongroup==1.3.1
      - faster-fifo==1.5.2
      - filelock==3.19.1
      - fonttools==4.60.2
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - ftfy==6.3.1
      - fvcore==0.1.5.post20221221
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.28.1
      - google-api-python-client==2.187.0
      - google-auth==2.43.0
      - google-auth-httplib2==0.2.1
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.72.0
      - grpcio==1.76.0
      - grpcio-status==1.71.2
      - gym==0.23.0
      - gym-notices==0.1.0
      - h11==0.16.0
      - h5py==3.14.0
      - habitat-baselines==0.3.3
      - habitat-lab==0.3.3
      - habitat-sim==0.3.3
      - hf-xet==1.2.0
      - hjson==3.1.0
      - httpcore==1.0.9
      - httplib2==0.31.0
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - hydra-core==1.3.2
      - idna==3.11
      - ifcfg==0.24
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.1
      - iopath==0.1.10
      - jinja2==3.1.6
      - joblib==1.5.3
      - lit==18.1.8
      - lmdb==1.7.5
      - markdown==3.9
      - markdown-it-py==3.0.0
      - markupsafe==3.0.3
      - mdurl==0.1.2
      - moviepy==2.2.1
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - multiprocess==0.70.18
      - networkx==3.2.1
      - ninja==1.13.0
      - nvidia-ml-py==13.590.44
      - objectio==0.2.29
      - omegaconf==2.3.0
      - opencv-python==4.9.0.80
      - orjson==3.11.5
      - pandas==2.3.3
      - peft==0.10.0
      - pillow==10.4.0
      - platformdirs==4.4.0
      - plyfile==1.1.3
      - pointnet2==0.0.0
      - portalocker==3.2.0
      - prefetch-generator==1.0.3
      - prettytable==3.16.0
      - proglog==0.1.12
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - psutil==7.1.3
      - py-cpuinfo==9.0.0
      - pyarrow==21.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyecharts==2.0.9
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dotenv==1.2.1
      - pytorch3d==0.7.8
      - pytz==2025.2
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.32.5
      - rich==13.9.4
      - rsa==4.9.1
      - safetensors==0.7.0
      - scikit-learn==1.6.1
      - sentencepiece==0.2.1
      - shellingham==1.5.4
      - simplejson==3.20.2
      - swanlab==0.7.4
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tokenizers==0.21.4
      - torch==2.1.2+cu118
      - torchvision==0.16.2+cu118
      - transformers==4.49.0
      - trimesh==2.35.39
      - triton==2.1.0
      - typer==0.21.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uritemplate==4.2.0
      - urllib3==2.6.1
      - wcwidth==0.2.14
      - webdataset==0.1.40
      - werkzeug==3.1.4
      - wrapt==2.0.1
      - xxhash==3.6.0
      - yacs==0.1.8
      - yarl==1.22.0
prefix: /home/isvl/.conda/envs/3DR1
